// Code generated by ogen, DO NOT EDIT.

package calm

import (
	"net/http"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/uri"
)

type GetCardParams struct {
	// ID of card to fetch.
	CardId string
}

func decodeGetCardParams(args [1]string, r *http.Request) (params GetCardParams, _ error) {
	// Decode path: cardId.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cardId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CardId = c
				return nil
			}(); err != nil {
				return params, err
			}
		} else {
			return params, errors.New("path: cardId: not specified")
		}
	}
	return params, nil
}
