// Code generated by ogen, DO NOT EDIT.
package payments

type CreateFinancialInstrumentRes interface {
	createFinancialInstrumentRes()
}

type CreateGatewayRes interface {
	createGatewayRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type CreateRuleRes interface {
	createRuleRes()
}

type CreateThreeDSAuthenticationRes interface {
	createThreeDSAuthenticationRes()
}

type CreateThreeDSProviderRes interface {
	createThreeDSProviderRes()
}

type CreateTransferRes interface {
	createTransferRes()
}

type CreateVerificationRes interface {
	createVerificationRes()
}

type DeleteFinancialInstrumentByIdRes interface {
	deleteFinancialInstrumentByIdRes()
}

type DeleteGatewayRes interface {
	deleteGatewayRes()
}

type DeleteRuleRes interface {
	deleteRuleRes()
}

type FinalizeTransferRes interface {
	finalizeTransferRes()
}

type GetFinancialInstrumentByIdRes interface {
	getFinancialInstrumentByIdRes()
}

type GetFinancialInstrumentsRes interface {
	getFinancialInstrumentsRes()
}

type GetGatewayByIdRes interface {
	getGatewayByIdRes()
}

type GetGatewaysRes interface {
	getGatewaysRes()
}

type GetRuleByIdRes interface {
	getRuleByIdRes()
}

type GetRulesRes interface {
	getRulesRes()
}

type GetTransferByIdRes interface {
	getTransferByIdRes()
}

type GetTransfersRes interface {
	getTransfersRes()
}

type OrdersOrderIDGetRes interface {
	ordersOrderIDGetRes()
}

type R3dsAuthentications3dsAuthenticationIDChallengesPostRes interface {
	r3dsAuthentications3dsAuthenticationIDChallengesPostRes()
}

type R3dsAuthentications3dsAuthenticationIDFingerprintsPostRes interface {
	r3dsAuthentications3dsAuthenticationIDFingerprintsPostRes()
}

type ReverseTransferByIdRes interface {
	reverseTransferByIdRes()
}

type UpdateGatewayByIdRes interface {
	updateGatewayByIdRes()
}

type UpdateRuleByIdRes interface {
	updateRuleByIdRes()
}
