// Code generated by ogen, DO NOT EDIT.

package vault

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

var _ Handler = UnimplementedHandler{}

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

// CreateAliases implements createAliases operation.
//
// Stores multiple values at once & returns their aliases.
// Alternatively, this endpoint may be used to associate additional (i.e.
// secondary) aliases with the same underlying data as the reference
// alias specified in the request body.
// **NOTE:** You cannot reference the same alias more than once in a
// single request.
//
// POST /aliases
func (UnimplementedHandler) CreateAliases(ctx context.Context, req OptCreateAliasesRequest) (r CreateAliasesCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAlias implements deleteAlias operation.
//
// Removes a single alias.
//
// DELETE /aliases/{alias}
func (UnimplementedHandler) DeleteAlias(ctx context.Context, params DeleteAliasParams) (r DeleteAliasNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// RevealAlias implements revealAlias operation.
//
// Retrieves a stored value along with its aliases.
// **NOTE:** This endpoint may expose sensitive data. Therefore, it is
// disabled by default. To enable it, please contact your VGS account
// manager or drop us a line at
// [support@verygoodsecurity.com](mailto:support@verygoodsecurity.com).
//
// GET /aliases/{alias}
func (UnimplementedHandler) RevealAlias(ctx context.Context, params RevealAliasParams) (r RevealedData, _ error) {
	return r, ht.ErrNotImplemented
}

// RevealMultipleAliases implements revealMultipleAliases operation.
//
// Given a list of aliases, retrieves all associated values stored in the
// vault.
// **NOTE:** This endpoint may expose sensitive data. Therefore, it is
// disabled by default. To enable it, please contact your VGS account
// manager or drop us a line at
// [support@verygoodsecurity.com](mailto:support@verygoodsecurity.com).
//
// GET /aliases
func (UnimplementedHandler) RevealMultipleAliases(ctx context.Context, params RevealMultipleAliasesParams) (r RevealMultipleAliasesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAlias implements updateAlias operation.
//
// Apply new classifiers to the value that the specified alias is
// associated with.
//
// PUT /aliases/{alias}
func (UnimplementedHandler) UpdateAlias(ctx context.Context, req OptUpdateAliasRequest, params UpdateAliasParams) (r UpdateAliasNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates ApiErrorsResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r ApiErrorsResponseStatusCode) {
	return r
}
