// Code generated by ogen, DO NOT EDIT.

package vault

import (
	"time"
)

// SetFake set fake values.
func (s *Alias) SetFake() {
	{
		{
			s.Alias.SetFake()
		}
	}
	{
		{
			s.Format.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AliasFormat) SetFake() {
	*s = AliasFormatFPEACCNUMTFOUR
}

// SetFake set fake values.
func (s *ApiError) SetFake() {
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Href.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Title.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ApiErrorsResponse) SetFake() {
	{
		{
			s.Errors = nil
			for i := 0; i < 1; i++ {
				var elem ApiError
				{
					elem.SetFake()
				}
				s.Errors = append(s.Errors, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateAliasesCreated) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem RevealedData
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateAliasesRequest) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 1; i++ {
				var elem CreateAliasesRequestDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateAliasesRequestDataItem) SetFake() {
	var elem CreateAliasesRequestDataItem0

	{
		elem.SetFake()
	}
	s.SetCreateAliasesRequestDataItem0(elem)
}

// SetFake set fake values.
func (s *CreateAliasesRequestDataItem0) SetFake() {
	{
		{
			s.Classifiers = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Classifiers = append(s.Classifiers, elem)
			}
		}
	}
	{
		{
			s.Format.SetFake()
		}
	}
	{
		{
			s.Storage.SetFake()
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateAliasesRequestDataItem0Storage) SetFake() {
	*s = CreateAliasesRequestDataItem0StoragePERSISTENT
}

// SetFake set fake values.
func (s *CreateAliasesRequestDataItem1) SetFake() {
	{
		{
			s.Alias = "string"
		}
	}
	{
		{
			s.Format.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OptAliasFormat) SetFake() {
	var elem AliasFormat
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateAliasesRequest) SetFake() {
	var elem CreateAliasesRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateAliasesRequestDataItem0Storage) SetFake() {
	var elem CreateAliasesRequestDataItem0Storage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDateTime) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptRevealedDataStorage) SetFake() {
	var elem RevealedDataStorage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUpdateAliasRequest) SetFake() {
	var elem UpdateAliasRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *RevealMultipleAliasesOK) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem RevealedData
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *RevealedData) SetFake() {
	{
		{
			s.Aliases = nil
			for i := 0; i < 0; i++ {
				var elem Alias
				{
					elem.SetFake()
				}
				s.Aliases = append(s.Aliases, elem)
			}
		}
	}
	{
		{
			s.Classifiers = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Classifiers = append(s.Classifiers, elem)
			}
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.Storage.SetFake()
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *RevealedDataStorage) SetFake() {
	*s = RevealedDataStoragePERSISTENT
}

// SetFake set fake values.
func (s *UpdateAliasRequest) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateAliasRequestData) SetFake() {
	{
		{
			s.Classifiers = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Classifiers = append(s.Classifiers, elem)
			}
		}
	}
}
