// Code generated by ogen, DO NOT EDIT.

package vault

// setDefaults set default value of fields.
func (s *CreateAliasesRequestDataItem0) setDefaults() {
	{
		val := CreateAliasesRequestDataItem0Storage("PERSISTENT")
		s.Storage.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RevealedData) setDefaults() {
	{
		val := RevealedDataStorage("PERSISTENT")
		s.Storage.SetTo(val)
	}
}
